theme: jekyll-theme-minimal
show_downloads: false
title: Thomas G. Stewart
description: <i>Data scientist, Biostatistician, Clinical trialist</i><br><br><b>School of Data Science<br>University of Virginia</b>
encoding: UTF-8
