theme: jekyll-theme-minimal
show_downloads: false
title: Thomas G. Stewart<br><i>Data scientist, Biostatistician, Clinical trialist</i>
description: <b>School of Data Science<br>University of Virginia</b>
encoding: UTF-8
