theme: jekyll-theme-minimal
show_downloads: false
title: 
description: <b>Data Science Institute<br>Vanderbilt University</b><br><br><b>Department of Biostatistics<br>Vanderbilt University Medical Center</b><br><br><b>VICTR Research Methods</b>
encoding: UTF-8
