remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
title: Thomas G. Stewart
description: <i>Data scientist specializing in<br>Biostatistics & Trial design</i><br><br><b>Associate professor<br>School of Data Science<br>University of Virginia</b>
encoding: UTF-8
